[package]
name = "rir-lir"
version = "0.1.0"
authors = ["Jasper den Hertog <jasper@plainspace.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "^0.3"
ansi_term = "^0.12"
chrono = "0.4.19"
csv = "^1.1"
hyper = { version = "0.14.9", features = [ "full" ] }
rotonda-store = { git = "ssh://git@github.com/NLnetLabs/rotonda-store.git", branch = "feature-dynamodb" }
rustyline = "8.0.0"
tokio = { version = "1.7.1", features = [ "macros", "rt-multi-thread", "sync" ] }
