[package]
name = "rir-lir"
version = "0.1.0"
authors = ["Jasper den Hertog <jasper@plainspace.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "^0.3"
csv = "^1.1"
rotonda-store = { path = "/Users/jasper/Projects/rotonda/rotonda-store"}
ansi_term = "^0.12"
rustyline = "8.0.0"
