#!/bin/bash

# Create the whole dir if it doesn't exist
# Also move the exsiting files into downloads/_/old
if [ -d downloads/riswhois/old ];then
    mv -f downloads/riswhois/riswhois* downloads/ris_whois/old/
else
    mkdir -p downloads/riswhois/old
fi

echo RISWHois IPv4
curl -o downloads/riswhois/riswhoisdump-ipv4.gz http://www.ris.ripe.net/dumps/riswhoisdump.IPv4.gz
gunzip downloads/riswhois/riswhoisdump-ipv4.gz

echo RISWhois IPv6
curl -o downloads/riswhois/riswhoisdump-ipv6.gz http://www.ris.ripe.net/dumps/riswhoisdump.IPv6.gz
gunzip downloads/riswhois/riswhoisdump-ipv6.gz

echo Refactor RISWhois
rg -e '(\d+)\t(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/(\d+)\t(\d+)' -N --replace '$2,$3,$1' downloads/riswhois/riswhoisdump-ipv4 > data/pfx_asn_dfz_v4.csv
rg -e '(\d+)\t([0-9abcdef:]+)/(\d{1,3})\t(\d+)$' -N --replace '$2,$3,$1' downloads/riswhois/riswhoisdump-ipv6 > data/pfx_asn_dfz_v6.csv
