#!/bin/bash

# Create the whole dir if it doesn't exist
# Also move the exsiting files into downloads/_/old
if [ -d downloads/del_ext/old ];then
    mv -f downloads/del_ext/delegated-* downloads/del_ext/old/
else
   mkdir -p downloads/del_ext/old
fi

echo delegated-afrinic-extended-latest
curl -o downloads/del_ext/delegated-afrinic-extended-latest.txt ftp://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest

echo delegated-apnic-extended-latest
curl -o downloads/del_ext/delegated-apnic-extended-latest.txt ftp://ftp.apnic.net/pub/stats/apnic/delegated-apnic-extended-latest

echo delegated-arin-extended-latest
curl -o downloads/del_ext/delegated-arin-extended-latest.txt ftp://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest

echo delegated-lacnic-extended-latest
curl -o downloads/del_ext/delegated-lacnic-extended-latest.txt ftp://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest

echo delegated-ripencc-extended-latest
curl -o downloads/del_ext/delegated-ripencc-extended-latest.txt ftp://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest

echo concatenate all
cat downloads/del_ext/delegated-afrinic-extended-latest.txt > data/delegated_all.csv && \
cat downloads/del_ext/delegated-apnic-extended-latest.txt >> data/delegated_all.csv && \
cat downloads/del_ext/delegated-arin-extended-latest.txt >> data/delegated_all.csv && \
cat downloads/del_ext/delegated-lacnic-extended-latest.txt >> data/delegated_all.csv && \
cat downloads/del_ext/delegated-ripencc-extended-latest.txt >> data/delegated_all.csv
