#!/bin/bash

# only works on Linux

# move to the dir of the repo
cd "$(dirname "$0")"
cd ..

# Create the whole dir if it doesn't exist
# Also move the exsiting files into downloads/_/old
if [ -d downloads/riswhois/old ];then
    mv -f downloads/riswhois/riswhois* downloads/ris_whois/old/
else
    mkdir -p downloads/riswhois/old
fi

if [ ! -d data ]; then
   mkdir data
fi

echo RISWHois IPv4
curl -Ro downloads/riswhois/riswhoisdump-ipv4.gz https://www.ris.ripe.net/dumps/riswhoisdump.IPv4.gz
gunzip -f downloads/riswhois/riswhoisdump-ipv4.gz

echo RISWhois IPv6
curl -Ro downloads/riswhois/riswhoisdump-ipv6.gz https://www.ris.ripe.net/dumps/riswhoisdump.IPv6.gz
gunzip -f downloads/riswhois/riswhoisdump-ipv6.gz

echo Refactor RISWhois
rg -e '(\d+)\t(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/(\d+)\t(\d+)' -N --replace '$2,$3,$1' downloads/riswhois/riswhoisdump-ipv4 > data/pfx_asn_dfz_v4.csv
rg -e '(\d+)\t([0-9abcdef:]+)/(\d{1,3})\t(\d+)$' -N --replace '$2,$3,$1' downloads/riswhois/riswhoisdump-ipv6 > data/pfx_asn_dfz_v6.csv

echo write timestamps
echo { > data/riswhois.timestamps.json
echo \"ipv4\": `stat -c %Y downloads/riswhois/riswhoisdump-ipv4`, >> data/riswhois.timestamps.json
echo \"ipv6\": `stat -c %Y downloads/riswhois/riswhoisdump-ipv6`, >> data/riswhois.timestamps.json
echo } >> data/riswhois.timestamps.json
