#!/bin/bash
# only works on Linux

if [ $1 != "--all" ] && [ "$1" != "afrinic" ] && [ $1 != "apnic" ] && [ $1 != "arin" ] && [ $1 != "lacnic" ] && [ $1 != "ripencc" ]; then
  echo "download delegated extended files from RIRs"
  echo "usage: download-del-ext [afrinic|apinic|arin|lacnic|ripencc| --all]"
  exit 0
fi

# move to the dir of the repo this script is in
cd "$(dirname "$0")"
cd ..

# Create the whole dir if it doesn't exist
# Also move the exsiting files into downloads/_/old
if [ -d downloads/del_ext/old ];then
    mv -f downloads/del_ext/delegated-"$1"-extended-latest.txt downloads/del_ext/old/
else
   mkdir -p downloads/del_ext/old
fi

if [ ! -d data ];then
  mkdir data
fi

if [ $1 = "afrinic" ] || [  $1 = "--all" ]; then
  echo download delegated-afrinic-extended-latest
  curl -RsD downloads/afrinic_h.txt -o downloads/del_ext/delegated-afrinic-extended-latest.txt https://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest
fi

if [ $1 = "apnic" ] || [ $1 = "--all" ]; then
echo download delegated-apnic-extended-latest
curl -RsD downloads/apnic_h.txt -o downloads/del_ext/delegated-apnic-extended-latest.txt https://ftp.apnic.net/stats/apnic/delegated-apnic-extended-latest
fi

if [ $1 = "arin" ] || [ $1 = "--all" ]; then
echo download delegated-arin-extended-latest
curl -RsD downloads/arin_h.txt -o downloads/del_ext/delegated-arin-extended-latest.txt https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest
fi

if [ $1 = "lacnic" ] || [ $1 = "--all" ]; then
echo download delegated-lacnic-extended-latest
curl -RsD downloads/lacnic_h.txt -o downloads/del_ext/delegated-lacnic-extended-latest.txt https://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest
fi

if [ $1 = "ripencc" ] || [ $1 = "--all" ]; then
echo download delegated-ripencc-extended-latest
curl -RsD downloads/ripencc_h.txt -o downloads/del_ext/delegated-ripencc-extended-latest.txt https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest
fi

echo concatenate all
cat downloads/del_ext/delegated-afrinic-extended-latest.txt > data/delegated_all.csv && \
cat downloads/del_ext/delegated-apnic-extended-latest.txt >> data/delegated_all.csv && \
cat downloads/del_ext/delegated-arin-extended-latest.txt >> data/delegated_all.csv && \
cat downloads/del_ext/delegated-lacnic-extended-latest.txt >> data/delegated_all.csv && \
cat downloads/del_ext/delegated-ripencc-extended-latest.txt >> data/delegated_all.csv

echo write timestamps
echo { > data/del_ext.timestamps.json
echo \"afrinic\": { >> data/del_ext.timestamps.json
echo -e '\t"file_timestamp": '`stat -c %Y downloads/del_ext/delegated-afrinic-extended-latest.txt`, >> data/del_ext.timestamps.json
echo -e '\t"last_modified_header": "'`cat downloads/afrinic_h.txt | rg -e '^Last-Modified: ([\w,0-9 :]+)' --only-matching --replace '$1'`'"' >> data/del_ext.timestamps.json
echo -e '},' >> data/del_ext.timestamps.json
echo \"apnic\": { >> data/del_ext.timestamps.json 
echo -e '\t"file_timestamp": '`stat -c %Y downloads/del_ext/delegated-apnic-extended-latest.txt`, >> data/del_ext.timestamps.json
echo -e '\t"last_modified_header": "'`cat downloads/apnic_h.txt | rg -e '^Last-Modified: ([\w,0-9 :]+)' --only-matching --replace '$1'`'"' >> data/del_ext.timestamps.json
echo -e '}.' >> data/del_ext.timestamps.json
echo \"arin\": { >> data/del_ext.timestamps.json 
echo -e '\t"file_timestamp": '`stat -c %Y downloads/del_ext/delegated-arin-extended-latest.txt`, >> data/del_ext.timestamps.json
echo -e '\t"last_modified_header": "'`cat downloads/arin_h.txt | rg -e '^Last-Modified: ([\w,0-9 :]+)' --only-matching --replace '$1'`'"' >> data/del_ext.timestamps.json
echo -e '},' >> data/del_ext.timestamps.json
echo \"lacnic\": { >> data/del_ext.timestamps.json 
echo -e '\t"file_timestamp": '`stat -c %Y downloads/del_ext/delegated-lacnic-extended-latest.txt`, >> data/del_ext.timestamps.json
echo -e '\t"last_modified_header": "'`cat downloads/lacnic_h.txt | rg -e '^Last-Modified: ([\w,0-9 :]+)' --only-matching --replace '$1'`'"' >> data/del_ext.timestamps.json
echo -e '},' >> data/del_ext.timestamps.json
echo \"ripencc\": { >> data/del_ext.timestamps.json
echo -e '\t"file_timestamp": '`stat -c %Y downloads/del_ext/delegated-ripencc-extended-latest.txt`, >> data/del_ext.timestamps.json
echo -e '\t"last_modified_header": "'`cat downloads/ripencc_h.txt | rg -e '^Last-Modified: ([\w,0-9 :]+)' --only-matching --replace '$1'`'"' >> data/del_ext.timestamps.json
echo -e '}' >> data/del_ext.timestamps.json
echo } >> data/del_ext.timestamps.json
