#!/bin/bash
# move to the dir of the repo this script is in
cd "$(dirname "$0")"
cd ..

changed=false

for rir in afrinic,https://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest, \
	apnic,https://ftp.apnic.net/stats/apnic/delegated-apnic-extended-latest, \
	arin,https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest, \
	lacnic,https://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest,  \
	ripencc,https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest, \
;do IFS=","
	set -- $rir
	echo ----------------------------------
	echo "$1" | tr [a-z] [A-Z]
	cur_ts=`cat downloads/"$1"_h.txt | rg -e '^Last-Modified: (.+)$' --replace '$1'`
	echo local download time: $cur_ts

	next_ts=`curl -s --HEAD $2 | rg -e '^Last-Modified: (.+)$' --replace '$1'`
	echo remote download time: $next_ts

	if [ "$cur_ts" = "$next_ts" ]; then
		echo UNCHANGED
	else
		echo CHANGED
		changed=true
		echo downloading $2
		scripts/download-del-ext "$1"
	fi
done

if [ $changed = true ]; then
echo -------------------
	echo restarting roto-api daemon...
	systemctl restart roto-api
else
	echo no updates, exiting...
fi
