#!/bin/bash


arg="$1"
if [ "$arg" != "" ] && [ "$arg" != "--dry-run" ] && [ "$arg" != "--force-sync" ]; then
  echo "download delegated extended files from RIRs"
  echo "usage: update-status-riswhois [--dry-run|--force-sync]"
  echo
  echo "set envvar ROTO_API_PEER to sync to peer"
  exit 0
fi

if [ "$ROTO_API_PEER" = "" ] && [ "$arg" != "--dry-run" ]; then
  echo "Error: Set envvar ROTO_API_PEER to sync to peer"
  exit 1
fi

# move to the dir of the repo this script is in
cd "$(dirname "$0")"
cd ..

changed=false

for riswhois in \
	riswhois4,www.ris.ripe.net/dumps/riswhoisdump.IPv4.gz, \
	riswhois6,www.ris.ripe.net/dumps/riswhoisdump.IPv6.gz \
;do IFS=","
	set -- $riswhois
	echo ----------------------------------
	echo "$1" | tr [a-z] [A-Z]
	cur_ts=`cat downloads/"$1"_h.txt | /home/roto/.cargo/bin/rg -e '^Last-Modified: (.+)$' --replace '$1'`
	echo local download time: $cur_ts

	next_ts=`curl -s --HEAD $2 | /home/roto/.cargo/bin/rg -e '^Last-Modified: (.+)$' --replace '$1'`
	echo remote download time: $next_ts

	if [ "$cur_ts" = "$next_ts" ]; then
            echo UNCHANGED
	else
	    echo CHANGED
	    "$changed" = true
	    if [ "$arg" != "--dry-run" ]; then
	       echo downloading $2
	       scripts/download-riswhois "$1"
	       if [ $1 = "riswhois6" ]; then
	            echo "restarting roto-api daemon..."
		    XDG_RUNTIME_DIR="/run/user/1000" \
                    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" \
		    systemctl --user restart roto-api
	       else
	            echo no new ipv6 files, exiting...
	       fi
            fi
	fi
done

if [ "$changed" = true ] || [ "$arg" == "--force-sync" ]; then
    echo sending this to peer...
    rsync -Cavz --delete data/ "$ROTO_API_PEER":/home/roto/ris_alloc_api/data/
    ssh roto@"$ROTO_API_PEER" "systemctl --user restart roto-api"
else
    echo nothing changed, skipping writing to "$ROTO_API_PEER".
fi
