name: Packaging

on:
  push:
    branches:
      - "main"
    tags:
      - v*

  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: |
          echo "Hello World!"
