name: Packaging

on:
  push:
    branches:
      - "main"
    tags:
      - v*

  # Triggering on PRs and arbitrary branch pushes is not enabled because most of the time only the CI build should be
  # triggered, not the packaging build. In cases where you want to test changes to this workflow this trigger enables
  # you to manually invoke this workflow on an arbitrary branch as needed.
  workflow_dispatch:

jobs:
  package:
    #
    # Set @vN to the latest released version.
    # For more information see: https://github.com/NLnetLabs/ploutos/blob/main/README.md
    #
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v7

    #
    # Docker related 'secrets' and 'with' settings are optional unless you set 'docker_build_rules'.
    #
    secrets:
      DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      docker_org: nlnetlabs
      docker_repo: roto-api
      docker_build_rules: pkg/rules/docker-images-to-build.yml

      package_build_rules: pkg/rules/packages-to-build.yml

	  rpm_scriptlets_path: pkg/rpm/scriptlets.toml